model:
    name: Cover
    block_l:
    - sequential_l:
        - component_l:
            - [Conv2d, {'in_channels':-1, 'out_channels':256, 'kernel_size':[12, 180], 'stride':[1,1]}]
            - [Activation, PReLU]
            - [MaxPool2d, {'kernel_size':[12, 1], 'stride': [1, 1]}]
        - component_l:
            - [Conv2d, {'in_channels':-1, 'out_channels':256, 'kernel_size':[1, 5], 'stride':[1,1]}]
            - [Activation, PReLU]
        - component_l:
            - [Conv2d, {'in_channels':-1, 'out_channels':256, 'kernel_size':[1, 5], 'stride':[1,1]}]
            - [Activation, PReLU]
        - component_l:
            - [Conv2d, {'in_channels':-1, 'out_channels':256, 'kernel_size':[1, 5], 'stride':[1,1]}]
            - [Activation, PReLU]
        - component_l:
            - [Conv2d, {'in_channels':-1, 'out_channels':256, 'kernel_size':[1, 5], 'stride':[1,1]}]
            - [Activation, PReLU]
    - sequential_l:
        - component_l:
#           - [Max, {'dim':3, 'keepdim':True}]
#            - [Mean, {'dim':3, 'keepdim':True}]
#            - [SoftmaxWeight, empty]
#            - [AutoPoolWeight, empty]
            - [AutoPoolWeightSplit, empty]
        - component_l:
            - [Squeeze, {'dim': [2,3]}]
            - [Linear, {'in_features':-1, 'out_features':32}]
#           - [Activation, Sigmoid]
            #- [Activation, Tanh]
            - [BatchNorm1d, {'num_features': -1, 'affine': False}]